# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np
ar = np.arange(start = 0, stop = 99, step = 1)
ar*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [2]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [3]:

np.full(100,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [4]:
import numpy;
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [9]:
arr = [[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]]
arr[2] = [1,1,1]
arr[1] = [3,2,1]
arr


[[0.0, 2.0, 4.0], [3, 2, 1], [1, 1, 1]]

#### 6. Создать вектор со значениями от 10 до 100

In [10]:
np.arange(10,101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [11]:
v = np.arange(10)
v[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [12]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [15]:
v = np.array([1,2,3,4,5])
nz = 3

v0 = np.zeros(len(v) + (len(v)-1)*(nz))

v0[::nz+1] = v
v0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [17]:

np.random.random((3,3,3))

array([[[0.04413156, 0.46302864, 0.67860701],
        [0.05234109, 0.19732585, 0.79432425],
        [0.0581283 , 0.70508186, 0.83835809]],

       [[0.05647853, 0.93404189, 0.98901777],
        [0.16136711, 0.3908221 , 0.0910706 ],
        [0.96398617, 0.26001188, 0.66636239]],

       [[0.35865408, 0.77981479, 0.65476157],
        [0.37432248, 0.14061046, 0.30107224],
        [0.49887413, 0.12919464, 0.34611875]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [18]:
v = np.random.random((10,10))
vmin = v.min()
vmax =  v.max()
vmin

0.017752123080756688

In [20]:
vmax

0.996881858110481

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [21]:
np.random.random(30).mean()

0.40241411084812156

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [22]:
v = np.ones((10,10))
v[1:-1,1:-1] = 0
v

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [23]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [25]:
v = np.zeros((8,8), dtype=int)

v[1::2,::2] = 1
v[::2,1::2] = 1
v

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [26]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [27]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [28]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [29]:
v = np.arange(100)
v[(3 < v) & (v <= 8)] *= -1
v

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [30]:
v = np.zeros((5,5))
v += np.arange(5)
v

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24. Есть генератор, сделать с его помощью массив

In [31]:
def fun():
    for i in range(100):
        yield i
a = np.fromiter(fun(),dtype=float,count=-1)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [32]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [43]:
a = np.random.random(100)
a.sort()
a

array([0.00626453, 0.03899671, 0.04810699, 0.05827339, 0.06531956,
       0.09765421, 0.09914356, 0.09932723, 0.11658654, 0.11727093,
       0.12645823, 0.15296611, 0.16238712, 0.17676134, 0.18285435,
       0.21283948, 0.21824606, 0.22590155, 0.2260516 , 0.23008594,
       0.23388944, 0.2458068 , 0.24784217, 0.24830155, 0.27058479,
       0.28384588, 0.28914843, 0.30302182, 0.30511366, 0.31265595,
       0.31573281, 0.31943047, 0.37643819, 0.37728084, 0.37729154,
       0.37755023, 0.39316064, 0.40797912, 0.41504853, 0.43161568,
       0.45522943, 0.46320501, 0.46744888, 0.48359726, 0.48709985,
       0.50555707, 0.50633311, 0.51110926, 0.51865914, 0.52600533,
       0.52609402, 0.52998002, 0.53855927, 0.53937923, 0.58869397,
       0.61396575, 0.61428851, 0.61500438, 0.68558845, 0.69389563,
       0.70247108, 0.70405985, 0.71044232, 0.71129091, 0.71216961,
       0.73202617, 0.73605196, 0.73824424, 0.76498896, 0.76756821,
       0.77283319, 0.77528368, 0.77854491, 0.78869442, 0.82443

#### 27. Проверить, одинаковы ли 2 numpy массива

In [44]:
a1 = np.array([1,1,1])
a2 = np.array([1,1,1])
np.allclose(a1,a2)

True

#### 28. Сделать массив неизменяемым

In [45]:
a = np.zeros(10).flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [46]:
a = np.arange(10000)
np.random.shuffle(a)

n = 5
a[np.argpartition(-a,n)[:n]]

array([9999, 9998, 9996, 9997, 9995])

#### 30. Заменить максимальный элемент на ноль

In [48]:
a = np.random.random(30)
a[a.argmax()] = 0
a

array([0.78293112, 0.94476022, 0.94245135, 0.77188979, 0.65488267,
       0.34839971, 0.13805706, 0.60229209, 0.65478745, 0.        ,
       0.56192264, 0.8214667 , 0.23590981, 0.26511519, 0.49943914,
       0.23129747, 0.34318026, 0.70392282, 0.25738284, 0.20282589,
       0.82292756, 0.5798086 , 0.67945108, 0.26676879, 0.3235294 ,
       0.6545548 , 0.46590219, 0.32917937, 0.14039179, 0.29038166])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [49]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
a

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [50]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
c

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [51]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [52]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [59]:
np.set_printoptions(threshold=np.nan)
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [54]:
ar1 = np.arange(100)
ar2 = np.random.uniform(0,100)
num = (np.abs(ar1-ar2)).argmin()
ar1[num]

80

#### 36. Преобразовать массив из float в int

In [55]:
ar = np.arange(10, dtype=np.float32)
ar = ar.astype(np.int32, copy=False)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [56]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [65]:
n = 5
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
Z

array([[0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.]])

#### 39. Отнять среднее из каждой строки в матрице

In [67]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

#### 40. Отсортировать матрицу по n-ому столбцу

In [68]:
Z = np.random.randint(0,10,(3,3))
n = 1 
print(Z)
print(Z[Z[:,n].argsort()])

[[6 1 4]
 [2 6 9]
 [4 4 7]]
[[6 1 4]
 [4 4 7]
 [2 6 9]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [69]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [70]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 5. 4. 2. 4. 3. 2. 2. 3.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [71]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [72]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[69 56 73 62]
 [48 27 56 68]
 [68 49 54 54]]
